name: FunKraftMultiBrain
author: SlowFeew
version: 1.0
main: fun.slowfeew.multibrain.Main
load: STARTUP
depend:
  - ProtocolLib
  - FunKraftCore
commands:
  setspawn:
    permission: op
    description: Set the spawn point for the game
  forcestart:
    permission: GameMaster
    description: Force start the game
  multibrain:
    aliases:
      - mb
    permission: op
    description: MultiBrain command
  test:
    permission: op
    description: Test command
  debug:
    permission: op
    description: Debug command